---
- name: Changing System attributes on Cisco devices to default
  connection: local
  hosts: ios
  gather_facts: false

  tasks:
  
  - name: Executing system parameter changes
    ios_system:
      state: absent
